export const  TechnologyDemandRef = 
 
   [
	{
		"Power Builder": "0",
		"Lotus Notes Scripting": "0",
		"COBOL/CICS": "0",
		"IMS/JCL": "0",
		"CPAS": "0",
		"Filenet Report Manager": "0",
		"WDP UI": "0",
		"WDP Microservices": "0",
		"WDP BPEL": "0",
		"WDP BPM": "0",
		"Base24(Tandem)": "0",
		"FileNet Image Server": "0",
		"Microsoft SQL Server": "0",
		"Java": "6",
		"Coding ": "3",
		"Analytical ": "3",
		"Bootstrap": "0",
		"C# Net": "0",
		"PL SQL": "3",
		"Unix": "3",
		"VB .Net": "0",
		"Webservice": "6",
		"JavaScript": "0",
		"Hibernate": "3",
		"Spring": "3",
		"EJB": "6",
		"Filenet": "6",
		"J2EE": "3",
		"Angular JS": "0",
		"WebSphere Application ServerL": "3",
		"WebSphere MQ": "0",
		"XML": "0",
		"Splunk": "3",
		"TALLYMAN Collections and Configuration": "0",
		"Devops": "3",
		"DB2 / SQL": "3",
		"Control-M": "6",
		"HTML": "3",
		"Jenkins": "3"
	},
	{
		"Power Builder": "0",
		"Lotus Notes Scripting": "0",
		"COBOL/CICS": "0",
		"IMS/JCL": "0",
		"CPAS": "0",
		"Filenet Report Manager": "0",
		"WDP UI": "0",
		"WDP Microservices": "6",
		"WDP BPEL": "0",
		"WDP BPM": "3",
		"Base24(Tandem)": "0",
		"FileNet Image Server": "0",
		"Microsoft SQL Server": "0",
		"Java": "9",
		"Coding ": "6",
		"Analytical ": "3",
		"Bootstrap": "0",
		"C# Net": "0",
		"PL SQL": "3",
		"Unix": "3",
		"VB .Net": "0",
		"Webservice": "9",
		"JavaScript": "0",
		"Hibernate": "6",
		"Spring": "6",
		"EJB": "6",
		"Filenet": "3",
		"J2EE": "0",
		"Angular JS": "0",
		"WebSphere Application ServerL": "0",
		"WebSphere MQ": "0",
		"XML": "0",
		"Splunk": "0",
		"TALLYMAN Collections and Configuration": "0",
		"Devops": "0",
		"DB2 / SQL": "9",
		"Control-M": "6",
		"HTML": "6",
		"Jenkins": "6"
	},
	{
		"Power Builder": "0",
		"Lotus Notes Scripting": "0",
		"COBOL/CICS": "0",
		"IMS/JCL": "0",
		"CPAS": "0",
		"Filenet Report Manager": "0",
		"WDP UI": "0",
		"WDP Microservices": "3",
		"WDP BPEL": "6",
		"WDP BPM": "6",
		"Base24(Tandem)": "0",
		"FileNet Image Server": "6",
		"Microsoft SQL Server": "0",
		"Java": "9",
		"Coding ": "6",
		"Analytical ": "3",
		"Bootstrap": "0",
		"C# Net": "0",
		"PL SQL": "3",
		"Unix": "3",
		"VB .Net": "0",
		"Webservice": "6",
		"JavaScript": "0",
		"Hibernate": "6",
		"Spring": "6",
		"EJB": "6",
		"Filenet": "6",
		"J2EE": "0",
		"Angular JS": "0",
		"WebSphere Application ServerL": "0",
		"WebSphere MQ": "0",
		"XML": "0",
		"Splunk": "0",
		"TALLYMAN Collections and Configuration": "0",
		"Devops": "0",
		"DB2 / SQL": "6",
		"Control-M": "3",
		"HTML": "6",
		"Jenkins": "6"
	}
]